name: cd-deploy-azure

on:
  workflow_run:
    workflows: [ "ci-default" ]
    types: [ completed ]
    branches: [ "main" ]  # asegura que sólo despliegue si el CI vino de main

permissions:
  contents: read

env:
  AZURE_WEBAPP_NAME: webapp-tfe-unir-dev
  AZURE_WEBAPP_PACKAGE_PATH: '.'

concurrency:
  group: deploy-${{ github.ref || github.event.workflow_run.head_branch || 'main' }}
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: Development

    steps:
      - name: Download artifact from CI run
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: net-app
          path: ./app
          repo: ${{ github.repository }}
          if_no_artifact_found: fail

      - name: Download deploy metadata (optional)
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: deploy-metadata
          path: ./meta
          repo: ${{ github.repository }}
          if_no_artifact_found: ignore

      - name: Read metadata and override vars (if present)
        if: ${{ hashFiles('./meta/deploy-metadata.json') != '' }}
        run: |
          echo "AZURE_WEBAPP_NAME_OVERRIDE=$(jq -r '.azure_webapp_name // empty' ./meta/deploy-metadata.json)" >> $GITHUB_ENV
        shell: bash

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_OVERRIDE || env.AZURE_WEBAPP_NAME }}
          package: ./app
